const express = require('express')
const cors = require('cors')
const homeRouter = require('./routes/homeRouter')
const userRouter = require('./routes/userRouter')
const loginRouter = require('./routes/loginRouter')
const bankRouter = require('./routes/bankRouter')
const transactionRouter = require('./routes/transactionRouter')
const balancesDashboardRouter = require('./routes/balancesRouter')
const extractPageRouter = require('./routes/extractPageRouter')
const newTransactionRouter = require('./routes/newTransactionRouter')
const planningRouter = require('./routes/planningRouter')
const dashboardRouter = require('./routes/dashboardRouter')

require('./database').start()
global.logger = require('../config/logger')
const app = express()
app.use(cors({ origin: '*', methods: '*' }))
app.use(express.json())
app.use(express.urlencoded({ extended: false }))

app.use('/', homeRouter)
app.use('/user', userRouter)
app.use('/login', loginRouter)
app.use('/bank', bankRouter)
app.use('/transaction', transactionRouter)
app.use('/balances-dashboard', balancesDashboardRouter)
app.use('/extract-page', extractPageRouter)
app.use('/new-transaction', newTransactionRouter)
app.use('/planing', planningRouter)
app.use('/dashboards', dashboardRouter)

module.exports = app
