name: Deploy

on: 
  pull_request:
    types:
      - closed
    branches:
      - release
      - main

jobs:
  build:
    name: Build and Deploy (${{ github.ref_name }})
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy')
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      - name: Create deployment package
        run: zip -qq -r bundle.zip ./config ./src node_modules package.json package-lock.json index.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION --zip-file fileb://bundle.zip
