name: Homologation Deploy
on:
  push:
    branches:
      - release
jobs:
  tf_fmt:
    name: Deploy Site
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: '-var="lambda_zip=bundle.zip"'
          # lambda_zip: bundle.zip
          # lambda_name: 'sgf-backend-test'
          # arn_role: '${{ secrets.IAM_ARN }}'
          # db_username: '${{ secrets.DB_USERNAME }}'
          # db_password: '${{ secrets.IAM_ARN }}'
          # key_token: '${{ secrets.KEY_TOKEN }}'
        # with:
        #   variables: |
        #     lambda_zip = bundle.zip
        #     lambda_name = "sgf-backend-test"
        #     arn_role = "${{ secrets.IAM_ARN }}"
        #     db_username = "${{ secrets.DB_USERNAME }}"
        #     db_password = "${{ secrets.IAM_ARN }}"
        #     key_token = "${{ secrets.KEY_TOKEN }}"
